---
title: "About"
---

Though I was born and raised in Virginia, my career in the Air Force eventually brought me to Texas, where I have lived for the past five years while continuing to grow both personally and professionally. I’m currently pursuing a Master’s degree in Social Data Analytics & Research (graduating May 2026) because I believe in the importance of data-driven decision making.

But how did I find myself at the doorstep of data? Over the last 8+ years, I’ve built experience in behavioral health, program management, and policy evaluation through work in community, hospital, military, and government settings. Along the way, I realized that while systems and processes are designed to improve quality of life, many don’t always function as intended. And when proposals for new or revised programs are made, they often require evidence and research to guide the best path forward. For me, the most objective and balanced way forward is through the use of data, while also recognizing its limitations and the importance of having people in these spaces who can apply it effectively.

Through this education, I aspire to bridge clinical insight with strategic thinking to improve how support services are delivered. My goal is to ensure that programs not only exist, but actually work as intended, and when they don’t, that I have the skills to redesign them in ways that create meaningful, sustainable change.

## Interests

-   Urban planning and neighborhood development
-   Social determinants of health
-   Data-driven approaches to improving community outcomes
-   Geographic Information Systems (GIS) for spatial analysis

## Certifications and Licenses

-   Licensed Clinical Social Worker (LCSW-Supervisor) – Texas & Virginia

-   Project Management Professional (PMP)

-   Board Certified Diplomate (BCD), Clinical Social Work

## Contact

LinkedIn: [https://linkedin.com/in/tyerelldotson](https://www.linkedin.com/in/tyerelldotson/)
